'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Afoot

    '''<summary>
    '''mutiview1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mutiview1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''viewshow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewshow As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''hdfmode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfmode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfIDNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIDNew As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNew As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvData As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hdfSortField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSortField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfSortDirectoin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSortDirectoin As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPage As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblAllPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllPage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewadd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewadd As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tbnamedept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbnamedept As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbheadfoot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbheadfoot As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbmidfoot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbmidfoot As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbfootfoot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbfootfoot As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnback As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''viewedit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewedit As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''tbEnamedept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEnamedept As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbEheadfoot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEheadfoot As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbEmidfoot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEmidfoot As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbEfootfoot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEfootfoot As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnEsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEsave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnEback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEback As Global.System.Web.UI.WebControls.LinkButton
End Class
